### ISSUE TITLE
If no README.md is present in folder, error throws

### ISSUE THREAD

**Issue by kylemh** [RichardLitt/generator-standard-readme#31]
As a user, I should expect to run `standard-readme` and be prompted with questions.

Instead, if I don't have a `README.md` in my project, this error gets thrown:
```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/kylemh/Path_To_Git_Repo/README.md'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Function.readSync (/Users/kmh/.nvm/versions/node/v7.10.0/lib/node_modules/standard-readme/node_modules/to-vfile/lib/fs.js:56:22)
    at Object.<anonymous> (/Users/kmh/.nvm/versions/node/v7.10.0/lib/node_modules/standard-readme/index.js:10:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

**Comment by RichardLitt** [comment]
Unable to reproduce. I suspect you have [RichardLitt/standard-readme](https://github.com/RichardLitt/standard-readme) installed, and you're seeing that package instead. Can you run `npm uninstall -g standard-readme` and try again?

**Comment by kylemh** [comment]
@RichardLitt if I didn't have RichardLitt/standard-readme installed running `standard-readme` in the CLI yielded no "Command not found".

**Comment by kylemh** [comment]
Of course, since you've removed the installation instructions that I used, this issue may no longer be relevant!

I did not attempt installing using Yeoman.

**Comment by RichardLitt** [comment]
Yep! Install yeoman and this should be good. Right? :)

**Comment by RichardLitt** [comment]
Awesome. Thanks, @kylemh!
